name: carnitas_cheque
description: POS móvil para puesto de carnitas — Fase 1 Local-Only.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Base de datos local reactiva
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # Estado predecible
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Gráficas KPI
  fl_chart: ^0.70.2
  print_bluetooth_thermal: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
